before:
  hooks:
    - go mod download

project_name: mymy

builds:
  - env:
      - CGO_ENABLED=1
    main: ./cmd/mymy/main.go
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.buildDate={{.Date}}
    goarch:
      - amd64
    goos:
      - linux

archives:
  - files:
      - LICENSE
      - README.md
      - config/mymy.conf.yml

checksum:
  name_template: 'checksums.txt'
  # Algorithm to be used.
  # Accepted options are sha256, sha512, sha1, crc32, md5, sha224 and sha384.
  # Default is sha256.
  algorithm: sha256

snapshot:
  name_template: "{{ .Tag }}-SNAPSHOT-{{.ShortCommit}}"

changelog:
  skip: true

nfpms:
  - id: default
    package_name: mymy

    maintainer: Pavel Parshin <p.parshin@city-mobil.ru>
    homepage: https://github.com/city-mobil/go-mymy
    description: MySQL - MySQL replicator
    license: MIT

    formats:
      - deb
      - rpm

    dependencies: ~
    recommends:
      - mysql-client
    suggests: ~
    conflicts: ~

    bindir: /usr/local/bin

    epoch: 1
    release: 1

    scripts:
      postinstall: "scripts/postinstall.sh"
      preremove: "scripts/preremove.sh"

    files:
      "scripts/etc/systemd/**": "/etc/systemd/system"

    config_files:
      "config/mymy.conf.yml": "/etc/mymy/conf.yml"