version: '3.4'

services:
  source:
    image: mysql:${MYSQL_SRC_VERSION:-8.0.22}
    environment:
      - MYSQL_DATABASE=city
      - MYSQL_USER=repl
      - MYSQL_PASSWORD=repl
      - MYSQL_ROOT_PASSWORD=root_pwd
    command: --bind-address=0.0.0.0 --ssl=0 --default-authentication-plugin=mysql_native_password --log-bin=mysql-bin --server-id=1 --enforce_gtid_consistency=ON --gtid_mode=ON
    volumes:
      - ./docker/source/init.d:/docker-entrypoint-initdb.d
    ports:
      - '13306:3306'

  upstream:
    image: mysql:${MYSQL_DST_VERSION:-8.0.22}
    environment:
      - MYSQL_DATABASE=town
      - MYSQL_USER=repl
      - MYSQL_PASSWORD=repl
      - MYSQL_ROOT_PASSWORD=root_pwd
    command: --bind-address=0.0.0.0 --ssl=0 --default-authentication-plugin=mysql_native_password
    volumes:
      - ./docker/upstream/init.d:/docker-entrypoint-initdb.d
    ports:
      - '13307:3306'