name: golangci-lint

on:
  push:
    tags:
      - v*
    branches:
      - main
  pull_request:
    branches:
      - '*'

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.32.2